### ISSUE TITLE
using an index.html

### ISSUE THREAD

**Issue by fuxing-at** [tywmick/php-todo#1]
Hallo!

I really like your Tool and I'm a complete rookie.
So I have to ask if there even would be any possibility to use your tool in an an html file?

thanks

**Comment by TyMick** [comment]
Hi, JP! HTML doesn't really allow for any interactivity (unless you inline JavaScript with [`<script>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) tags, which I don't recommend). If you want to get started learning what HTML can and can't do and then move on to JavaScript for building interactive apps, I highly recommend [freeCodeCamp](https://www.freecodecamp.org/)—that's how I got started.
